### ISSUE TITLE
Setup travis ci

### ISSUE THREAD

**Issue by thisislawatts** [imgix-wordpress/images-via-imgix#11]
🙃  

[![Build Status](https://travis-ci.org/imgix-wordpress/imgix-wordpress.svg?branch=master)](https://travis-ci.org/imgix-wordpress/imgix-wordpress)

**Comment by rasmusbe** [comment]
I can probably get them working, looking at it right now

**Comment by rasmusbe** [comment]
I have made some progress, the tests are now running but failing.
I will continue to look in to the tests tomorrow.
https://travis-ci.org/rasmusbe/imgix-wordpress/builds/195243473

**Comment by rasmusbe** [comment]
The tests should be working now, but you have to activate travis on the new repo name.
