### ISSUE TITLE
Publish this repo to packagist

### ISSUE THREAD

**Issue by rasmusbe** [imgix-wordpress/images-via-imgix#17]
It would be great if this plugin was added to packagist to enable support for installation via composer.

**Comment by thisislawatts** [comment]
Sounds like a good plan to help with the project visibility. I will take a look at setting up an account for the organisation.

Have you used [wppackagist](https://wpackagist.org/) before, could be a useful stop gap.

Are you using this plugin on any live projects at the moment?

**Comment by rasmusbe** [comment]
Yes, wpackagist is good as well, but it mirrors the WordPress svn instead of github, and I guess I will find the code on github before I find it on the SVN (when testing next release).
If you need help setting it up I'm willing to help.

I don't use it live yet, but I'm implementing a imgix solution for [BabyBjörn](https://www.babybjorn.com/) right now.

**Comment by rasmusbe** [comment]
The plugin is now live on https://www.babybjorn.com

**Comment by thisislawatts** [comment]
🚀 Congrats on launch, looks great. May I congratulate you on those snappy image loading times 👌

**Comment by rasmusbe** [comment]
Thank you, thou I'm using the develop-branch from my fork right now, which includes the fixes in #18, and #20 and #21

**Comment by thisislawatts** [comment]
Sounds good. Fully committed at work this week, but hoping to get sometime over the weekend to work through these PRs. Got some WordPress work scheduled in the next few weeks so will have more availability

**Comment by thisislawatts** [comment]
✨ https://packagist.org/packages/imgix-wordpress/images-via-imgix

Let me know if there's anything else you'd like to see included from a Packagist perspective.
