### ISSUE TITLE
Mangled src URLs

### ISSUE THREAD

**Issue by dwightgunning** [imgix-wordpress/images-via-imgix#23]
I've just installed via a repo .zip download (024a9379310e6ef848bc4fe78fcfefddfc49a306)...

All images in my templates work as expected. Unfortunately, the images in my posts are being mangled.

Without the plugin enabled, the img element is being modified by WP to include a srcset attribute. 

This seems to be being parsed incorrectly once the imgix plugin is enabled.

I'm hoping somebody has seen this before???

Post "source":

`<img class="alignnone size-full wp-image-1483" src="https://getstream.io/blog/wp-content/uploads/2016/11/image01.png" alt="Imgix - CDN" width="640" height="320" />`

HTML page source with imgix plugin **disabled**:

`<img src="https://getstream.io/blog/wp-content/uploads/2016/11/image01.png" alt="Imgix - CDN" width="640" height="320" class="alignnone size-full wp-image-1483" srcset="https://getstream.io/blog/wp-content/uploads/2016/11/image01.png 640w, https://getstream.io/blog/wp-content/uploads/2016/11/image01-300x150.png 300w, https://getstream.io/blog/wp-content/uploads/2016/11/image01-610x305.png 610w" sizes="(max-width: 639px) 98vw, (max-width: 1199px) 64vw, 640px" />`

HTML page source with imgix plugin **enabled**:

`<img src="https://getstream.io/blog/wp-content/uploads/2016/11/image01.png%20alt=Imgix%20-%20CDN%20width=640%20height=320%20class=alignnone%20size-full%20wp-image-1483%20srcset=https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?auto=format,enhance%20640w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=300&#038;h=150&#038;auto=format,enhance%20300w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=610&#038;h=305&#038;auto=format,enhance%20610w%20sizes=(max-width:%20639px)%2098vw,%20(max-width:%201199px)%2064vw,%20640px" srcset="https://getstream.io/blog/wp-content/uploads/2016/11/image01.png%20alt=Imgix%20-%20CDN%20width=640%20height=320%20class=alignnone%20size-full%20wp-image-1483%20srcset=https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?auto=format,enhance%20640w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=300&#038;h=150&#038;auto=format,enhance%20300w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=610&#038;h=305&#038;auto=format,enhance%20610w%20sizes=(max-width:%20639px)%2098vw,%20(max-width:%201199px)%2064vw,%20640px, https://getstream.io/blog/wp-content/uploads/2016/11/image01.png%20alt=Imgix%20-%20CDN%20width=640%20height=320%20class=alignnone%20size-full%20wp-image-1483%20srcset=https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?auto=format,enhance%20640w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=300&#038;h=150&#038;auto=format,enhance%20300w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=610&#038;h=305&#038;auto=format,enhance%20610w%20sizes=(max-width:%20639px)%2098vw,%20(max-width:%201199px)%2064vw,%20640px&amp;dpr=2 2x, https://getstream.io/blog/wp-content/uploads/2016/11/image01.png%20alt=Imgix%20-%20CDN%20width=640%20height=320%20class=alignnone%20size-full%20wp-image-1483%20srcset=https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?auto=format,enhance%20640w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=300&#038;h=150&#038;auto=format,enhance%20300w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=610&#038;h=305&#038;auto=format,enhance%20610w%20sizes=(max-width:%20639px)%2098vw,%20(max-width:%201199px)%2064vw,%20640px&amp;dpr=3 3x," srcset="https://getstream.io/blog/wp-content/uploads/2016/11/image01.png%20alt=Imgix%20-%20CDN%20width=640%20height=320%20class=alignnone%20size-full%20wp-image-1483%20srcset=https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?auto=format,enhance%20640w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=300&#038;h=150&#038;auto=format,enhance%20300w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=610&#038;h=305&#038;auto=format,enhance%20610w%20sizes=(max-width:%20639px)%2098vw,%20(max-width:%201199px)%2064vw,%20640px, https://getstream.io/blog/wp-content/uploads/2016/11/image01.png%20alt=Imgix%20-%20CDN%20width=640%20height=320%20class=alignnone%20size-full%20wp-image-1483%20srcset=https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?auto=format,enhance%20640w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=300&#038;h=150&#038;auto=format,enhance%20300w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=610&#038;h=305&#038;auto=format,enhance%20610w%20sizes=(max-width:%20639px)%2098vw,%20(max-width:%201199px)%2064vw,%20640px&amp;dpr=2 2x, https://getstream.io/blog/wp-content/uploads/2016/11/image01.png%20alt=Imgix%20-%20CDN%20width=640%20height=320%20class=alignnone%20size-full%20wp-image-1483%20srcset=https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?auto=format,enhance%20640w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=300&#038;h=150&#038;auto=format,enhance%20300w,%20https://getstream-blog.imgix.net/blog/wp-content/uploads/2016/11/image01.png?w=610&#038;h=305&#038;auto=format,enhance%20610w%20sizes=(max-width:%20639px)%2098vw,%20(max-width:%201199px)%2064vw,%20640px&amp;dpr=3 3x," />`

**Comment by thisislawatts** [comment]
Hey @dwightgunning, Thanks for flagging this up.
Those are certainly some mangled URL's you're getting there. I believe that @rasmusbe has written a fix for this bug which I've merged this. Could try with the latest version of the .zip from the master?

**Comment by dwightgunning** [comment]
Just got around to testing this fix with a zipped download at e20ab837c175406f3d4efb576d9b3c81c5985acb.

Looks good to me. Thanks!!!!

**Comment by thisislawatts** [comment]
Thanks for confirming @dwightgunning. Not a problem at all, we've all got long to do lists I'm sure!

I'll close out this issue and get the latest fixes pushed across to the plugins repo.
