### ISSUE TITLE
Plugin triggers multiple PHP warnings on activation due to include statements for scripts that don't exist 

### ISSUE THREAD

**Issue by RobertCalise** [imgix-wordpress/images-via-imgix#25]
For example:
```Warning: include(includes/compability.php): failed to open stream: No such file or directory in wp-content/plugins/images-via-imgix/imgix.php on line 19```

and 
```Warning: include(includes/class-images-via-imgix.php): failed to open stream: No such file or directory in wp-content/plugins/images-via-imgix/imgix.php on line 20```

It looks like the version of this plugin on Github is a bit out of sync with what exists on SVN and the WP plugins directory, since I see this `compability.php` file when I clone the repo, but not in the plugin that I have installed through WP.

**Comment by thisislawatts** [comment]
Thanks for flagging @RobertCalise, will push an updated version shortly. Up this hasn't held you up too much. Let me know if you've got any questions.

**Comment by RobertCalise** [comment]
Nope - once I realized what was going on, I was able to just swap out the installed plugin for master.zip from this repo. Thanks, @thisislawatts!

**Comment by thisislawatts** [comment]
🎺  New version up on the WordPress plugin directory, thanks again for the heads up.
