### ISSUE TITLE
Get this plugin listed on WordPress' directory

### ISSUE THREAD

**Issue by thisislawatts** [imgix-wordpress/images-via-imgix#7]

**Comment by thisislawatts** [comment]
A bit of back and forth on some minor code tweaks, but ultimately looks like we're going to have to figure out a new name for this which doesn't conflict with the imgix namespace.

So any ideas? 

_Response from the WordPress plugin team below_


On review we cannot accept this plugin.

Your plugin has been rejected because you do not appear to work for or legally represent imgix organisation.

The tl;dr here is that If you don't legally work for or represent someone, you cannot begin your plugin name with the term(s) of their products.


WE KNOW THEY HAVE GIVEN YOU PERMISSION. Sadly, in our experience, that has backfired too many times, and we cannot permit it. If you're not OFFICIALLY them, you cannot use THEIR name.

A longer explanation follows. Please read before you press reply.
 
We're no longer accepting plugins that begin with (or are in total) a trademarked product name or term, or a commonly understood brand, as the name or slug of a plugin (ex: facebook or google-maps-bathrooms). Nor are we accepting plugins that include the name of another plugin at the beginning of the name/slug (eg: contact-form-7-music). Similarly, we extend this to projects (open or closed source) in the interests of protecting their 'brand.'
 
We also do not accept "permission" from companies for you to use this, because we do not wish to be involved in potential issues later on when they may revoke permission. Simply put, don't use someone ELSE'S name as the very first term (or terms) in YOUR plugin. 
 
The slug for your plugin is generated based on the name you enter on the app plugin page, with hypens inserted in place of spaces. This means if you were to name your plugin "My Really Cool Cookie Jam" then your URL on WordPress.org would be http://wordpress.org/plugins/my-really-cool-cookie-jam

This becomes a larger issue when plugins use the names of other plugins in their own.

For example, if you have written an add-on plugin for WooCommerce, you may not name it "WooCommerce Improved Product Search" as that would generate the slug "woocommerce-improved-product-search" and that would conflict with the trademark of 'WooCommerce.' That said, it would be acceptable to submit the name "Woo Improved Product Search" which would use the slug "woo-improved-product-search" (woo not being trademarked you see).

As another example, if you have a plugin that integrates a service with a Easy Digital Downloads, you may call it "My Service Integration for Easy Digital Downloads", but you may not use "Easy Digital Downloads - My Service Integration". Alternately you could use 'EDD My Service Integration' and that too would be permitted.

None of this impacts your display name of your plugin. The display name is generated from your readme.txt, and that can be whatever you'd like. Keep in mind, you should use "My Product for Other Product" as the description. Consider the example of Keurig. If you made an eco-friendly brew cup, you could market it "EcoBrew Pod for Keurig" but you could NOT attempt to market it as "Keurig EcoBrew Pod." The latter implies a direct relationship to Keurig and may be against the law in some countries. 
 
You are more than welcome, and encouraged, to include it in the description of the plugin in the ReadMe.txt file, but it cannot be in the name/slug of the plugin as described above. 
 
Please resubmit this plugin with a better name and we will review it. If you're confused and want to check a name before resubmitting, just reply to this and ask :) 
 
http://wordpress.org/plugins/add/
 
(FYI - If this is incorrect and you DO work for that company or were legally hired to represent it in a developer capacity, please reply to this email and explain that to us. We base this decision off your email and the plugin's download link, among other things, so if you're using your personal gmail account and dropbox, that's PROBABLY why you got this. Hint hint ;) )

**Comment by thisislawatts** [comment]
After a bit of thought, I was thinking **images-via-imgix**, this resolves the WordPress plugin's concerns about including the `imgix` name. This way the plugin doesn't appear to be an official imgix extension.

Any objections let me know otherwise I will look to get this bundled up and resubmitted under the new name by the end of the week.

**Comment by rasmusbe** [comment]
I like the **images-via-imgix** name 👍

**Comment by thisislawatts** [comment]
![Have a great weekend!](https://media.giphy.com/media/3o72Fh8cCYPOOiBIvm/giphy.gif)


https://wordpress.org/plugins/images-via-imgix/
