### ISSUE TITLE
Add image check against domain

### ISSUE THREAD

**Issue by thisislawatts** [imgix-wordpress/images-via-imgix#8]
When adding/updating the imgix.net source, before saving it attempt to load an image via this URL.
* If an error state is returned then don't save domain/ or prevent filters being run on the imagery.

**Comment by rasmusbe** [comment]
I think this should be in the hands of the admin to enter an valid imgix url, not doing the verification in code. 

Adding an verification prevents developers from testing with invalid addresses and adds extra complexity to the plugin.

It also creates problems if `WP_HTTP_BLOCK_EXTERNAL` is defined

**Comment by thisislawatts** [comment]
I was thinking this would only be a client side cue
